### ISSUE TITLE
Please fix auto-launch at login bug

### ISSUE THREAD

**Issue by peterschussheim** [zeit/now-desktop#518] opened 2018-09-07 14:27 UTC
Related to #422, I am opening a new issue since that conversation has been locked to contributors.  [electron/electron#10880](https://github.com/electron/electron/issues/10880) has suggestions for fixes.

It is unacceptable that this has not been fixed.

**Comment by morajabi** [comment] 2018-09-08 12:30
I think a link to a tutorial for removing the app from login items manually on macOS would be helpful. (until we can solve it)

@peterschussheim Did you know you can remove it from login items manually, for yourself? https://macpaw.com/how-to/remove-startup-items-in-osx

**Comment by leo** [comment] 2018-09-08 13:36
Thank you for the effort you've put into this issue, but I'm going to close it as it's a duplicate of https://github.com/zeit/now-desktop/issues/422.

Once electron has fixed this, we can release a patch. Any of the other suggestions seem very hacky.

**Closed by leo** 2018-09-08 13:36 UTC
