### ISSUE TITLE
Unable to change preferences (macOS)

### ISSUE THREAD

**Issue by honzajavorek** [zeit/now-desktop#595] opened 2019-01-29 19:08 UTC
I'm unable to change preferences by clicking. I use macOS Mojave.

![kapture 2019-01-29 at 20 07 14](https://user-images.githubusercontent.com/283441/51933435-997a3100-2401-11e9-9dad-247090c23a58.gif)

**Comment by MAPESO** [comment] 2019-01-30 17:15
@leo some solution for this ?

**Comment by shinokada** [comment] 2019-02-04 08:34
I have the same problem. And also I am not able to quit. So that I am not able to remove the app.

**Comment by albinotonnina** [comment] 2019-03-08 23:09
Same problem, happens with Launch at Login option only in my case.

**Comment by f3l1x** [comment] 2019-03-09 11:01
Look's like electron bug.

Similar: 
- https://github.com/zeit/now-desktop/issues/422
- https://github.com/electron/electron/issues/10880#issuecomment-463114712

**Comment by juliangruber** [comment] 2019-03-09 11:12
Correct, closing as a duplicate of https://github.com/zeit/now-desktop/issues/422, please watch that issue.

**Closed by juliangruber** 2019-03-09 11:12 UTC
